### PR TITLE
Allow environment variables in the path

### PR DESCRIPTION
**Pull request by SimonKrughoff**
Our packaging system allows every package to set an environment variable pointing to its location.  We would like to distribute a package containing the cached dust maps so that not every user must cache the maps.  We do not know the absolute path to root install, but do know the environment variable with the path of the package containing the data.

Allowing environment variables in the `data_dir` path string would allow us to distribute and set up `dustmaps` to our users without any intervention on their end.

### CODE REVIEW

**Comment by SimonKrughoff** [comment]
I'm curious if this PR is something you'd be willing to take.  If not, I'm open to alternatives for doing a similar thing.  Thanks!

**Comment by gregreen** [comment]
Hi @SimonKrughoff, in principle this looks fine. Let me test this on my end before merging it.

**Comment by gregreen** [comment]
@SimonKrughoff, I've added some tests and documentation, and the code appears to be working fine. Thanks for this addition. I'm merging it into the develop branch. Let me know if you'd like me to package this change for pip.

**Comment by SimonKrughoff** [comment]
Having it packaged for pip would be great.  I'd like to start distributing this as a dependency of our code stack next week.

**Comment by SimonKrughoff** [comment]
Actually, we use conda for our Python package management.  Do I need to do anything to get this change propagated to conda-forge?

**Comment by gregreen** [comment]
I'm not sure - I've never packaged anything for conda. @wkerzendorf, do you know how this works?

**Comment by SimonKrughoff** [comment]
OK.  I see there is already a feedstock in conda-forge: https://github.com/conda-forge/dustmaps-feedstock.  I think that means if you make a release it should automatically build for conda-forge.

**Pull request merged**
